default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: pawel 
  password: pawel
  socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: my_blog
production:
  <<: *default
  database: my_blog 
